# .repo.toml

[about]
description = "Notes, links, and citations for presentations, videos, etc."
topics = ["just", "justfile", "youtube"]

[urls]
git_ssh = "git@github.com:chicks-net/presentation-notes.git"
web_url = "https://github.com/chicks-net/presentation-notes"

[flags]
claude = false
claude-review = false
copilot-review = false
standard-release = true
